### ISSUE TITLE
Backend breakage with optimizations off

### ISSUE THREAD

**Issue by sgraf812** [mj3-16/minijavac#133]
If we pass `MJ_OPTIMIZE=0`, the backend crashes:

```
java.lang.NullPointerException:     meta_call                                         /* Call T[77:14]; -> calloc_impl {0|Quad}[Con
                                                         st p64<0x1>[72:9]]|{1|Long}[Const Is<0x1>[2
                                                         12:48]] -> Optional[{2|Quad}[Call T[77:14]]
                                                         ] */: Argument {0|Quad}/*Const p64<0x1>[72:9]*/ doesn't exist
	at minijava.ir.assembler.allocator.OnTheFlyRegAllocator.visit(OnTheFlyRegAllocator.java:472)
	at minijava.ir.assembler.allocator.OnTheFlyRegAllocator.visit(OnTheFlyRegAllocator.java:23)
	at minijava.ir.assembler.instructions.MetaCall.accept(MetaCall.java:56)
	at minijava.ir.assembler.allocator.OnTheFlyRegAllocator.process(OnTheFlyRegAllocator.java:272)
	at minijava.ir.assembler.block.AssemblerFile.createForProgram(AssemblerFile.java:145)
	at minijava.Cli.printAsm(Cli.java:207)
	at minijava.Cli.compile(Cli.java:226)
	at minijava.Cli.run(Cli.java:94)
	at minijava.Main.main(Main.java:9)
```

**Comment by parttimenerd** [comment]
It seems to be bug that needs to be investigated.
The `meta_call` is easily fixable but fixing it leads to errors that are harder to debug.
